### ISSUE TITLE
Data attribute instead of own tag

### ISSUE THREAD

**Issue by frdmn** [geelen/x-gif#12]
Why did you create a new tag (`<x-gif>`) instead of an data attribute which could be appended to `<img>` like:

```
<img src="http://i.imgur.com/Ab4AUEX.jpg" data-x-gif>
```

or

```
<img src="http://i.imgur.com/Ab4AUEX.jpg" data-x-gif data-x-gif-speed="2.1"> 
```

The current solution is not really suitable for valid HTML.

**Comment by evolutionxbox** [comment]
I don't think that this project is too worried about valid HTML. Especially since something like this may never be valid HTML.

**Comment by frdmn** [comment]
@evolutionxbox Yeah, thats what I meant. But it could’ve been valid HTML if he just used an implementation like my example above. Or do I get it wrong?

**Comment by evolutionxbox** [comment]
I guess so. For myself, HTMl validation is more of a sanity check type tool than a rule.
Your implementation should work, but the x-component is a more clean solution (in my opinion).

**Comment by geelen** [comment]
This is a Web Component, currently implemented using Polymer, so I think a custom tag is pretty appropriate. The idea of 'Valid HTML' is an interesting one with custom elements - it seems like a reasonable target to say that any non-custom elements should be valid HTML5, and custom ones are simply valid XML?

Btw, because this tag needs to have children to show each of the frames in succession, you can't use an IMG tag, since that's a void element. So it'd have to be something like `<div data-x-gif>`, which I don't like particularly much.

**Comment by frdmn** [comment]
Thanks for the explanation @geelen!
